version: '3.9'

networks:
  my-network:
    driver: bridge

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    hostname: db_postgres
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - my-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    hostname: app
    ports:
      - '8086:8086'
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - my-network

volumes:
  postgres-db:
    driver: local
  app:
    driver: local
