version: '3.9'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    hostname: db_postgres
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
    driver: local
